#2.配置相关信息
#数据库配置
#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/test
#    username: root
#    password: 123456
    #springboot整合druid数据源方式一
#    type: com.alibaba.druid.pool.DruidDataSource

#springboot整合druid数据源方式二
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/test
      username: root
      password: 123456

mybatis:
  type-aliases-package: com.toxicant123.pojo #给pojo实体类起别名
  mapper-locations: classpath:mapper/*.xml #接口的配置文件的位置

