
###
GET http://localhost/books/1

###
POST http://localhost/books
Content-Type: application/json

{
  "type": "testData",
  "name": "testController",
  "description": "testController"
}

###
PUT http://localhost/books
Content-Type: application/json

{
  "id": 1,
  "type": "计算机理论",
  "name": "Spring实战 第5版",
  "description": "Spring入门经典教程，深入理解Spring原理技术内幕"
}

###
GET http://localhost:80/books

###
GET http://localhost:80/books/1/5